# Generated by Django 2.2.25 on 2022-02-04 19:08

from django.db import migrations, models
import django.db.models.deletion
import mibios.models
import mibios_umrad.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mibios', '0016_importfile_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('short_reference', models.CharField(help_text='short reference', max_length=128)),
                ('authors', models.CharField(blank=True, help_text='author listing', max_length=2048)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('abstract', models.TextField(blank=True)),
                ('key_words', models.CharField(blank=True, max_length=128)),
                ('publication', models.CharField(max_length=128)),
                ('doi', models.URLField()),
                ('history', models.ManyToManyField(to='mibios.ChangeRecord')),
            ],
            options={
                'unique_together': {('short_reference', 'publication')},
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(blank=True, help_text='accession to data set/study/project', max_length=32)),
                ('accession_db', models.CharField(blank=True, choices=[('NCBI', 'NCBI'), ('JGI', 'JGI'), ('Camera', 'Camera'), ('VAMPS', 'VAMPS')], help_text='Database associated with accession', max_length=8)),
                ('scheme', models.CharField(max_length=512, verbose_name='location and sampling scheme')),
                ('material_type', models.CharField(max_length=128)),
                ('water_bodies', models.CharField(help_text='list or description of sampled bodies of water', max_length=256)),
                ('primers', models.CharField(blank=True, max_length=64)),
                ('gene_target', models.CharField(blank=True, max_length=64)),
                ('sequencing_platform', models.CharField(blank=True, max_length=64)),
                ('size_fraction', models.CharField(blank=True, help_text='e.g.: >0.22µm or 0.22-1.6µm', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios_glamr.Reference')),
            ],
            options={
                'default_manager_name': 'objects',
                'unique_together': {('reference', 'accession', 'accession_db')},
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
    ]
