# Generated by Django 2.2.25 on 2022-03-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_glamr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='Volatile_suspended_solids',
            field=models.CharField(blank=True, max_length=64, verbose_name='Volatile Suspended Solids (mg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='absorbance',
            field=models.CharField(blank=True, max_length=64, verbose_name='Colored Dissolved Organic Material absorbance (m-1) at 400nm'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ammonia',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ammonia (µg N/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ctd_beam_attenuation',
            field=models.CharField(blank=True, max_length=64, verbose_name='CTD Beam Attenuation (m-1)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ctd_dissolved_oxygen',
            field=models.CharField(blank=True, max_length=64, verbose_name='CTD Dissolved Oxygen (mg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ctd_radiation',
            field=models.CharField(blank=True, max_length=64, verbose_name='CTD Photosynthetically Active Radiation (µE/m2/s)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ctd_specific_conductivity',
            field=models.CharField(blank=True, max_length=64, verbose_name='CTD Specific Conductivity (µS/cm)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ctd_temperature',
            field=models.CharField(blank=True, max_length=64, verbose_name='CTD Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ctd_tramission',
            field=models.CharField(blank=True, max_length=64, verbose_name='CTD Tramission (%)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='dissolved_microcystin',
            field=models.CharField(blank=True, max_length=64, verbose_name='Dissolved Microcystin (µg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='dissolved_organic_carbon',
            field=models.CharField(blank=True, max_length=64, verbose_name='Dissolved Organic Carbon (mg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='dissolved_phosphorus',
            field=models.CharField(blank=True, max_length=64, verbose_name='Total Dissolved Phosphorus (µg P/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='extracted_chlorophyll_a',
            field=models.CharField(blank=True, max_length=64, verbose_name='Extracted Chlorophyll a (µg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='extracted_phycocyanin',
            field=models.CharField(blank=True, max_length=64, verbose_name='Extracted Phycocyanin (µg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='fraction',
            field=models.CharField(blank=True, max_length=64, verbose_name='fraction'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='latitude',
            field=models.CharField(blank=True, max_length=64, verbose_name='Latitude (decimal deg)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='local_time',
            field=models.CharField(blank=True, max_length=64, verbose_name='Local Time (Eastern Time Zone)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='longitude',
            field=models.CharField(blank=True, max_length=64, verbose_name='Longitude (decimal deg)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='nitrate_nitrite',
            field=models.CharField(blank=True, max_length=64, verbose_name='Nitrate + Nitrite (mg N/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='organic_carbon',
            field=models.CharField(blank=True, max_length=64, verbose_name='Particulate Organic Carbon (mg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='organic_nitrogen',
            field=models.CharField(blank=True, max_length=64, verbose_name='Particulate Organic Nitrogen (mg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='particulate_microcystin',
            field=models.CharField(blank=True, max_length=64, verbose_name='Particulate Microcystin (µg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='phosphorus',
            field=models.CharField(blank=True, max_length=64, verbose_name='Total Phosphorus (µg P/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_depth',
            field=models.CharField(blank=True, max_length=64, verbose_name='Sample Depth (m)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_depth_category',
            field=models.CharField(blank=True, max_length=64, verbose_name='Sample Depth (category)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Sample_name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_temperature',
            field=models.CharField(blank=True, max_length=64, verbose_name='Sample Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='secchi_depth',
            field=models.CharField(blank=True, max_length=64, verbose_name='Secchi Depth (m)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='site',
            field=models.CharField(blank=True, max_length=64, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sky',
            field=models.CharField(blank=True, max_length=64, verbose_name='Sky'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='soluble_reactive_phosphorus',
            field=models.CharField(blank=True, max_length=64, verbose_name='Soluble Reactive Phosphorus (µg P/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='station_depth',
            field=models.CharField(blank=True, max_length=64, verbose_name='Station Depth (m)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='suspended_solids',
            field=models.CharField(blank=True, max_length=64, verbose_name='Total Suspended Solids (mg/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='turbidity',
            field=models.CharField(blank=True, max_length=64, verbose_name='Turbidity (NTU)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='urea',
            field=models.CharField(blank=True, max_length=64, verbose_name='Urea (µg N/L)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='wave_height',
            field=models.CharField(blank=True, max_length=64, verbose_name='Wave Height (ft)'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='wind_speed',
            field=models.CharField(blank=True, max_length=64, verbose_name='Wind speed (knots)'),
        ),
    ]
