# Generated by Django 2.2.26 on 2022-08-07 18:22

from django.db import migrations, models
import django.db.models.manager
import mibios_umrad.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_glamr', '0002_auto_20220806_1020'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reference',
            managers=[
                ('loader', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='bioproject',
            field=mibios_umrad.fields.AccessionField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='gold_id',
            field=mibios_umrad.fields.AccessionField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='jgi_project',
            field=mibios_umrad.fields.AccessionField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='other_databases',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='accession',
            field=mibios_umrad.fields.AccessionField(blank=True, default=None, help_text='accession to data set/study/project', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='accession_db',
            field=models.CharField(blank=True, choices=[('NCBI', 'NCBI'), ('JGI', 'JGI'), ('Camera', 'Camera'), ('VAMPS', 'VAMPS')], default='', help_text='Database associated with accession', max_length=8),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='gene_target',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='material_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='primers',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='scheme',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='location and sampling scheme'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='sequencing_data_type',
            field=models.CharField(blank=True, default='', help_text='e.g. amplicon, metagenome', max_length=128),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='short_name',
            field=models.CharField(blank=True, default=None, help_text='a short name or description, for internal use, not (necessarily) for public display', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='size_fraction',
            field=models.CharField(blank=True, default='', help_text='e.g.: >0.22µm or 0.22-1.6µm', max_length=32),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='water_bodies',
            field=models.CharField(blank=True, default='', help_text='list or description of sampled bodies of water', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('accession', 'bioproject', 'jgi_project', 'gold_id')},
        ),
    ]
