# Generated by Django 2.2.26 on 2022-08-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_glamr', '0003_auto_20220807_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='contigs_ok',
        ),
        migrations.AddField(
            model_name='sample',
            name='contig_abundance_loaded',
            field=models.BooleanField(default=False, help_text='contig abundance/rpkm data data loaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='contig_fasta_loaded',
            field=models.BooleanField(default=False, help_text='contig fasta data loaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gene_abundance_loaded',
            field=models.BooleanField(default=False, help_text='gene abundance/rpkm data loaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gene_alignment_hits_loaded',
            field=models.BooleanField(default=False, help_text='gene alignment hits to UniRef100 loaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='gene_fasta_loaded',
            field=models.BooleanField(default=False, help_text='gene fasta data loaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='meta_data_loaded',
            field=models.BooleanField(default=False, help_text='meta data successfully loaded'),
        ),
        migrations.AddField(
            model_name='sample',
            name='metag_pipeline_reg',
            field=models.BooleanField(default=False, help_text='is registered in metagenomic pipeline, has tracking ID'),
        ),
    ]
