# Generated by Django 2.2.24 on 2021-11-20 02:22

from django.db import migrations, models
import django.db.models.deletion
import mibios.models
import umrad.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mibios', '0016_importfile_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinMAX',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinMET93',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinMET97',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinMET99',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckM',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('translation_table', models.PositiveSmallIntegerField(verbose_name='Translation table')),
                ('gc_std', models.FloatField(verbose_name='GC std')),
                ('ambiguous_bases', models.PositiveIntegerField(verbose_name='# ambiguous bases')),
                ('genome_size', models.PositiveIntegerField(verbose_name='Genome size')),
                ('longest_contig', models.PositiveIntegerField(verbose_name='Longest contig')),
                ('n50_scaffolds', models.PositiveIntegerField(verbose_name='N50 (scaffolds)')),
                ('mean_scaffold_len', models.FloatField(verbose_name='Mean scaffold length')),
                ('num_contigs', models.PositiveIntegerField(verbose_name='# contigs')),
                ('num_scaffolds', models.PositiveIntegerField(verbose_name='# scaffolds')),
                ('num_predicted_genes', models.PositiveIntegerField(verbose_name='# predicted genes')),
                ('longest_scaffold', models.PositiveIntegerField(verbose_name='Longest scaffold')),
                ('gc', models.FloatField(verbose_name='GC')),
                ('n50_contigs', models.PositiveIntegerField(verbose_name='N50 (contigs)')),
                ('coding_density', models.FloatField(verbose_name='Coding density')),
                ('mean_contig_length', models.FloatField(verbose_name='Mean contig length')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContigCluster',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('seq_offset', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('seq_bytes', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('length', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('bases', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('coverage', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('reads_mapped', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('rpkm', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('frags_mapped', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('fpkm', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('cluster_id', umrad.fields.AccessionField(max_length=50, prefix='CLUSTER', unique=False)),
                ('bin_m93', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='umrad.BinMET93')),
                ('bin_m97', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='umrad.BinMET97')),
                ('bin_m99', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='umrad.BinMET99')),
                ('bin_max', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='umrad.BinMAX')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('seq_offset', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('seq_bytes', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('length', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('bases', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('coverage', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('reads_mapped', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('rpkm', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('frags_mapped', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('fpkm', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('gene_id', umrad.fields.AccessionField(max_length=50, prefix='CLUSTER', unique=False)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('strand', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1)),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.ContigCluster')),
            ],
        ),
        migrations.CreateModel(
            name='RNACentralRep',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniRef100',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=32, unique=True, verbose_name='UniRef100 accession')),
                ('protein_name', models.CharField(blank=True, default='', max_length=32)),
                ('taxonomic_lineage_id', models.CharField(blank=True, default='', max_length=32)),
                ('taxonomic_lineage_species', models.CharField(blank=True, default='', max_length=32)),
                ('organism', models.CharField(blank=True, default='', max_length=32)),
                ('dna_binding', models.CharField(blank=True, default='', max_length=32)),
                ('metal_binding', models.CharField(blank=True, default='', max_length=32)),
                ('signal_peptide', models.CharField(blank=True, default='', max_length=32)),
                ('transmembrane', models.CharField(blank=True, default='', max_length=32)),
                ('subcellular_location', models.CharField(blank=True, default='', max_length=32)),
                ('tcdb', models.CharField(blank=True, default='', max_length=32)),
                ('cog_kog', models.CharField(blank=True, default='', max_length=32)),
                ('pfam', models.CharField(blank=True, default='', max_length=32)),
                ('tigrfams', models.CharField(blank=True, default='', max_length=32)),
                ('kegg', models.CharField(blank=True, default='', max_length=32)),
                ('gene_ontology', models.CharField(blank=True, default='', max_length=32)),
                ('interpro', models.CharField(blank=True, default='', max_length=32)),
                ('ec_number', models.CharField(blank=True, default='', max_length=32)),
                ('history', models.ManyToManyField(to='mibios.ChangeRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleTaxonomyName',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField(choices=[(0, 'root'), (1, 'domain'), (2, 'phylum'), (3, 'class'), (4, 'order'), (5, 'family'), (6, 'genus'), (7, 'species'), (8, 'strain')])),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('rank', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SimpleTaxonomy',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('taxid', models.PositiveIntegerField(unique=True)),
                ('domain', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_dom_rel', to='umrad.SimpleTaxonomyName')),
                ('family', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_fam_rel', to='umrad.SimpleTaxonomyName')),
                ('genus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_gen_rel', to='umrad.SimpleTaxonomyName')),
                ('klass', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_cls_rel', to='umrad.SimpleTaxonomyName')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_ord_rel', to='umrad.SimpleTaxonomyName')),
                ('phylum', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_phy_rel', to='umrad.SimpleTaxonomyName')),
                ('species', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_sp_rel', to='umrad.SimpleTaxonomyName')),
                ('strain', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_str_rel', to='umrad.SimpleTaxonomyName')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', umrad.fields.AccessionField()),
                ('contigs_ok', models.BooleanField(default=False, help_text='Contig cluster data and coverage loaded')),
                ('binning_ok', models.BooleanField(default=False, help_text='Binning data loaded')),
                ('checkm_ok', models.BooleanField(default=False, help_text='Binning stats loaded')),
                ('genes_ok', models.BooleanField(default=False, help_text='Gene data and coverage loaded')),
                ('proteins_ok', models.BooleanField(default=False, help_text='Protein data loaded')),
                ('read_count', models.PositiveIntegerField(blank=True, default=None, help_text='number of reads used for assembly mapping', null=True)),
                ('reads_mapped', models.PositiveIntegerField(blank=True, default=None, help_text='number of reads mapped to assembly', null=True)),
                ('num_ref_sequences', models.PositiveIntegerField(blank=True, default=None, help_text='RefSequences number in coverage file header', null=True)),
                ('history', models.ManyToManyField(to='mibios.ChangeRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RNACentral',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', umrad.fields.AccessionField()),
                ('rna_type', models.PositiveSmallIntegerField(choices=[(1, 'antisense_RNA'), (2, 'autocatalytically_spliced_intron'), (3, 'guide_RNA'), (4, 'hammerhead_ribozyme'), (5, 'lncRNA'), (6, 'miRNA'), (7, 'misc_RNA'), (8, 'ncRNA'), (9, 'other'), (10, 'piRNA'), (11, 'precursor_RNA'), (12, 'pre_miRNA'), (13, 'ribozyme'), (14, 'RNase_MRP_RNA'), (15, 'RNase_P_RNA'), (16, 'rRNA'), (17, 'scaRNA'), (18, 'scRNA'), (19, 'siRNA'), (20, 'snoRNA'), (21, 'snRNA'), (22, 'sRNA'), (23, 'SRP_RNA'), (24, 'telomerase_RNA'), (25, 'tmRNA'), (26, 'tRNA'), (27, 'vault_RNA'), (28, 'Y_RNA')])),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.SimpleTaxonomy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadLibrary',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('fwd_qc0_fastq', umrad.fields.DataPathField(base='READS', default=None, max_length=1024, null=True)),
                ('rev_qc0_fastq', umrad.fields.DataPathField(base='READS', default=None, max_length=1024, null=True)),
                ('fwd_qc1_fastq', umrad.fields.DataPathField(base='READS', default=None, max_length=1024, null=True)),
                ('rev_qc1_fastq', umrad.fields.DataPathField(base='READS', default=None, max_length=1024, null=True)),
                ('raw_read_count', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('qc_read_count', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('history', models.ManyToManyField(to='mibios.ChangeRecord')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='umrad.Sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('seq_offset', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('seq_bytes', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('gene', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='umrad.Gene')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.Sample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gene',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.Sample'),
        ),
        migrations.AddField(
            model_name='contigcluster',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.Sample'),
        ),
        migrations.AddField(
            model_name='binmet99',
            name='checkm',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umrad.CheckM'),
        ),
        migrations.AddField(
            model_name='binmet99',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.Sample'),
        ),
        migrations.AddField(
            model_name='binmet97',
            name='checkm',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umrad.CheckM'),
        ),
        migrations.AddField(
            model_name='binmet97',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.Sample'),
        ),
        migrations.AddField(
            model_name='binmet93',
            name='checkm',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umrad.CheckM'),
        ),
        migrations.AddField(
            model_name='binmet93',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.Sample'),
        ),
        migrations.AddField(
            model_name='binmax',
            name='checkm',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umrad.CheckM'),
        ),
        migrations.AddField(
            model_name='binmax',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.Sample'),
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=32, unique=True, verbose_name='taxonomy ID')),
                ('source_db', models.PositiveSmallIntegerField(choices=[(0, 'ncbi')])),
                ('rank', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('name_type', models.CharField(blank=True, help_text='NCBI taxnonomy name type', max_length=32)),
                ('history', models.ManyToManyField(to='mibios.ChangeRecord')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umrad.Taxonomy')),
            ],
            options={
                'verbose_name_plural': 'taxa',
                'unique_together': {('source_db', 'rank', 'name', 'name_type')},
            },
        ),
        migrations.CreateModel(
            name='NCRNA',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('part', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('flag', models.PositiveIntegerField(help_text='bitwise FLAG')),
                ('pos', models.PositiveIntegerField(help_text='1-based leftmost mapping position')),
                ('mapq', models.PositiveIntegerField(help_text='MAPing Quality')),
                ('contig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.ContigCluster')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.RNACentralRep')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umrad.Sample')),
            ],
            options={
                'unique_together': {('sample', 'contig', 'part')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='gene',
            unique_together={('sample', 'gene_id')},
        ),
        migrations.AlterUniqueTogether(
            name='contigcluster',
            unique_together={('sample', 'cluster_id')},
        ),
        migrations.AlterUniqueTogether(
            name='binmet99',
            unique_together={('sample', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='binmet97',
            unique_together={('sample', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='binmet93',
            unique_together={('sample', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='binmax',
            unique_together={('sample', 'number')},
        ),
    ]
