# Generated by Django 2.2.13 on 2020-07-20 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('mibios', '0001_initial'), ('mibios', '0002_auto_20200713_1115'), ('mibios', '0003_auto_20200713_1153'), ('mibios', '0004_auto_20200714_0941'), ('mibios', '0005_auto_20200715_0032'), ('mibios', '0006_auto_20200717_1502'), ('mibios', '0007_auto_20200720_1451')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(null=True, upload_to='import/%Y/', verbose_name='data source file')),
                ('line', models.IntegerField(help_text='The corresponding line in the input file', null=True)),
                ('command_line', models.CharField(blank=True, help_text='management command for import', max_length=200)),
                ('record_pk', models.PositiveIntegerField()),
                ('record_natural', models.CharField(blank=True, max_length=300)),
                ('fields', models.TextField()),
                ('is_created', models.BooleanField(default=False, verbose_name='new record')),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'get_latest_by': 'timestamp',
                'ordering': ['-timestamp'],
            },
        ),
    ]
