# Generated by Django 2.2 on 2020-07-13 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mibios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ASV',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FecalSample',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH')),
                ('bristol', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('acetate_abs', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Acetate_mM')),
                ('acetate_rel', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Acetate_mmol_kg')),
                ('butyrate_abs', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Butyrate_mM')),
                ('butyrate_rel', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Butyrate_mmol_kg')),
                ('propionate_abs', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Propionate_mM')),
                ('propionate_rel', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Propionate_mmol_kg')),
            ],
            options={
                'ordering': ('participant', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('taxid', models.PositiveIntegerField()),
                ('organism', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.CharField(blank=True, max_length=30)),
                ('dose', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='total dose grams')),
                ('composition', models.CharField(blank=True, max_length=200, verbose_name='composition of the comsumed dietary supplement')),
            ],
            options={
                'ordering': ('composition', 'frequency', 'dose'),
                'unique_together': {('frequency', 'dose', 'composition')},
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('asv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.ASV')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
                ('path', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'ordering': ['serial', 'number'],
                'unique_together': {('serial', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('control', models.CharField(blank=True, choices=[('mock', 'mock'), ('water', 'water'), ('blank', 'blank'), ('plate', 'plate'), ('other', 'other')], max_length=50)),
                ('r1_file', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('r2_file', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('plate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plate_position', models.CharField(blank=True, max_length=10)),
                ('snumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.ManyToManyField(to='mibios.Note')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mibios.SequencingRun')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mibios.FecalSample')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('run', 'snumber'), ('run', 'plate', 'plate_position')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(choices=[('4', 'fall'), ('1', 'winter')], max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['year', 'term'],
                'unique_together': {('term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(blank=True, max_length=50)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=200)),
                ('quantity_compliant', models.CharField(blank=True, choices=[('NA', 'NA'), ('Quantity_compliant', 'Quantity_compliant'), ('no', 'no'), ('none', 'none'), ('unknown', 'unknown'), ('yes', 'yes')], help_text='Did the participant consumed at least 75% of the starch they were prescribed?', max_length=30)),
                ('has_consented', models.BooleanField(help_text='Corresponds to the Use_Data field in several original tables', null=True)),
                ('has_consented_future', models.BooleanField(help_text='Use Data in Unspecified Future Research', null=True)),
                ('has_consented_contact', models.CharField(blank=True, help_text='Contact for Future Study Participation', max_length=20)),
                ('saliva_status', models.CharField(blank=True, help_text='the "Saliva" field from the participant list', max_length=20)),
                ('supplement_status', models.CharField(blank=True, help_text='the "Supplement" field from the participant list', max_length=20)),
                ('blood_status', models.CharField(blank=True, help_text='the "Blood" field from the participant list', max_length=20)),
                ('note', models.ManyToManyField(to='mibios.Note')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mibios.Semester')),
                ('supplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Supplement')),
            ],
            options={
                'ordering': ['semester', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='note',
            field=models.ManyToManyField(to='mibios.Note'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios.Participant'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Week'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('asv', models.ManyToManyField(to='mibios.ASV')),
                ('seqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios.Sequencing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(null=True, upload_to='import/%Y/', verbose_name='data source file')),
                ('line', models.IntegerField(help_text='The corresponding line in the input file', null=True)),
                ('command_line', models.CharField(blank=True, help_text='management command for import', max_length=200)),
                ('record_model_name', models.CharField(max_length=100)),
                ('record_pk', models.IntegerField()),
                ('record_natural', models.CharField(blank=True, max_length=300)),
                ('fields', models.TextField()),
                ('is_created', models.BooleanField(verbose_name='new record')),
                ('is_deleted', models.BooleanField(verbose_name='deleted')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BreathSample',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('gases', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios.Participant')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Week')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('cytokines', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios.Participant')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Week')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asv',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Taxon'),
        ),
        migrations.AlterUniqueTogether(
            name='fecalsample',
            unique_together={('participant', 'number')},
        ),
    ]
