# Generated by Django 2.2.12 on 2020-06-09 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, max_length=30)),
                ('dose', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='total dose grams')),
                ('supplement', models.CharField(blank=True, max_length=200, verbose_name='supplement consumed')),
            ],
            options={
                'ordering': ('supplement', 'frequency', 'dose'),
                'unique_together': {('frequency', 'dose', 'supplement')},
            },
        ),
        migrations.CreateModel(
            name='FecalSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bristol', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_weight', models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True)),
                ('acetate_abs', models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Acetate_mM')),
                ('acetate_rel', models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Acetate_mmol_kg')),
                ('butyrate_abs', models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Butyrate_mM')),
                ('butyrate_rel', models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Butyrate_mmol_kg')),
                ('propionate_abs', models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Propionate_mM')),
                ('propionate_rel', models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Propionate_mmol_kg')),
            ],
            options={
                'ordering': ('participant__name', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(max_length=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.PositiveIntegerField()),
                ('organism', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.ASV')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
                ('path', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'ordering': ['serial', 'number'],
                'unique_together': {('serial', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('control', models.CharField(blank=True, choices=[('mock', 'mock'), ('water', 'water'), ('blank', 'blank'), ('plate', 'plate'), ('other', 'other')], max_length=50)),
                ('r1_file', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('r2_file', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('plate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plate_position', models.CharField(blank=True, max_length=10)),
                ('snumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.ManyToManyField(to='mibios.Note')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mibios.SequencingRun')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mibios.FecalSample')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('run', 'plate', 'plate_position'), ('run', 'snumber')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('4', 'fall'), ('1', 'winter')], max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-year', 'term'],
                'unique_together': {('term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(blank=True, max_length=50)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=200)),
                ('quantity_compliant', models.CharField(blank=True, choices=[('NA', 'NA'), ('Quantity_compliant', 'Quantity_compliant'), ('no', 'no'), ('none', 'none'), ('unknown', 'unknown'), ('yes', 'yes')], help_text='Did the participant consumed at least 75% of the starch they were prescribed?', max_length=30)),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Diet')),
                ('note', models.ManyToManyField(to='mibios.Note')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mibios.Semester')),
            ],
            options={
                'ordering': ['semester__year', 'semester__term', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='note',
            field=models.ManyToManyField(to='mibios.Note'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios.Participant'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Week'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asv', models.ManyToManyField(to='mibios.ASV')),
                ('seqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios.Sequencing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BreathSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gases', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios.Participant')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Week')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cytokines', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios.Participant')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Week')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='asv',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios.Taxon'),
        ),
        migrations.AlterUniqueTogether(
            name='fecalsample',
            unique_together={('participant', 'number')},
        ),
    ]
