# Generated by Django 2.2.13 on 2020-07-20 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0001_squashed_0007_auto_20200720_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerecord',
            name='record_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
