# Generated by Django 2.2 on 2020-06-30 19:03

from django.db import migrations, models
import mibios.models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year', 'term']},
        ),
        migrations.AddField(
            model_name='participant',
            name='blood_status',
            field=models.CharField(blank=True, help_text='the "Blood" field from the participant list', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='has_consented',
            field=models.BooleanField(help_text='Corresponds to the Use_Data field in several original tables', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='has_consented_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='has_consented_future',
            field=models.BooleanField(help_text='Use Data in Unspecified Future Research', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='saliva_status',
            field=models.CharField(blank=True, help_text='the "Saliva" field from the participant list', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='supplement_status',
            field=models.CharField(blank=True, help_text='the "Supplement" field from the participant list', max_length=20),
        ),
        migrations.AlterField(
            model_name='asv',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bloodsample',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='breathsample',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sequencingrun',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strain',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='week',
            name='id',
            field=mibios.models.AutoField(primary_key=True, serialize=False),
        ),
    ]
