# Generated by Django 2.2 on 2020-07-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asv',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='bloodsample',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='breathsample',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='community',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='note',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='participant',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='semester',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='sequencing',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='sequencingrun',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='strain',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='supplement',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
        migrations.AddField(
            model_name='week',
            name='history',
            field=models.ManyToManyField(to='mibios.ChangeRecord'),
        ),
    ]
