# Generated by Django 2.2.12 on 2020-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0002_auto_20200613_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecalsample',
            name='acetate_abs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Acetate_mM'),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='butyrate_abs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Butyrate_mM'),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='final_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='propionate_abs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Propionate_mM'),
        ),
    ]
