# Generated by Django 2.2.13 on 2020-07-23 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0002_auto_20200720_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerecord',
            name='fields',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='changerecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='import/%Y/', verbose_name='data source file'),
        ),
        migrations.AlterField(
            model_name='changerecord',
            name='line',
            field=models.IntegerField(blank=True, help_text='The corresponding line in the input file', null=True),
        ),
        migrations.AlterField(
            model_name='changerecord',
            name='record_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changerecord',
            name='record_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='changerecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
