# Generated by Django 2.2 on 2020-07-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mibios', '0003_auto_20200713_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerecord',
            name='record_model_name',
        ),
        migrations.AddField(
            model_name='changerecord',
            name='record_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changerecord',
            name='is_created',
            field=models.BooleanField(default=False, verbose_name='new record'),
        ),
        migrations.AlterField(
            model_name='changerecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='changerecord',
            name='record_pk',
            field=models.PositiveIntegerField(),
        ),
    ]
