# Generated by Django 2.2.13 on 2020-07-30 15:23
# and manually modified

from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    """
    Move ChangeRecord.file FileFields into ImportFile model

     * create ImportFile objects for each unique file name, but don't worry aboput storage here
     * extract the filename
     * set file field in ChangeRecord
    """
    ChangeRecord = apps.get_model('mibios', 'ChangeRecord')
    ImportFile = apps.get_model('mibios', 'ImportFile')

    for i in ChangeRecord.objects.all():
        if i.file_old:
            # get just the file's name
            _, _, name = i.file_old.name.rpartition('/')

            # assume no file has been imported twice under same name
            # but in future name won't be unique
            try:
                file_rec = ImportFile.objects.get(name=name)
            except ImportFile.DoesNotExist:
                file_rec = ImportFile(name=name, file=i.file_old)
                file_rec.full_clean()
                file_rec.save()

            i.file = file_rec
        else:
            # there is a FieldFile object but no filename
            # change not through file import
            i.file = None

        i.save()


def backward(apps, schema_editor):
    """
    Move ImportFile.file FileFields back into the ChangeRecord model
    """
    ChangeRecord = apps.get_model('mibios', 'ChangeRecord')
    for i in ChangeRecord.objects.all():
        if i.file is None:
            i.file_old = None  # becomes a FieldFile instance
        else:
            i.file_old = i.file.file

        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0003_auto_20200723_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=300, verbose_name='original filename')),
                ('file', models.FileField(upload_to='imported/%Y/', verbose_name='data source file')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.RenameField(
            model_name='changerecord',
            old_name='file',
            new_name='file_old',
        ),
        migrations.AddField(
            model_name='changerecord',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mibios.ImportFile'),
        ),
        migrations.RunPython(forward, reverse_code=backward),
        migrations.RemoveField(model_name='changerecord', name='file_old'),
    ]
