# Generated by Django 2.2.13 on 2020-07-31 15:22

from django.db import migrations, models
import mibios.models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0004_add_importfile_20200730_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=mibios.models._default_snapshot_name, max_length=100, unique=True)),
                ('dbfile', models.FilePathField(editable=False, path='/geomicro/data2/heinro/src/mibios/snapshots', verbose_name='archived database file')),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'database version',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AlterModelOptions(
            name='importfile',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'uploaded and imported file'},
        ),
    ]
