# Generated by Django 2.2 on 2020-07-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0004_auto_20200714_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerecord',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
