# Generated by Django 2.2 on 2020-07-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0005_auto_20200715_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerecord',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='acetate_abs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Acetate_mM'),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='butyrate_abs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Butyrate_mM'),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='final_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='propionate_abs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Propionate_mM'),
        ),
    ]
