# Generated by Django 2.2.14 on 2020-09-04 15:38

from django.db import migrations, models
import mibios.models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0006_snapshot_jsondump'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='app_list',
            field=models.CharField(default=mibios.models.Snapshot.get_app_list, editable=False, help_text='Comma-separated list of names of the apps that have data tables stored in the snapshot.', max_length=1000),
        ),
    ]
