# Generated by Django 2.2.14 on 2020-09-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0009_snapshot_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='name',
            field=models.CharField(help_text='This is the original, human-readable name for this file. It is allowed to have the same name for multiple imported file records.  This practice is encouraged e.g. if the same file is uploaded multiple times, e.g. re-uploading after making offline changes to the file.', max_length=300, verbose_name='original filename'),
        ),
    ]
