# Generated by Django 2.2.14 on 2020-10-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0010_auto_20200923_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='log',
            field=models.TextField(blank=True, default='', help_text='log output from data import'),
        ),
    ]
