# Generated by Django 2.2.14 on 2020-10-16 15:05

from django.db import migrations, models
import mibios.models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0011_importfile_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagNote',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(db_index=True, default='info', max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, max_length=5000)),
                ('history', models.ManyToManyField(to='mibios.ChangeRecord')),
            ],
            options={
                'verbose_name': 'note',
            },
        ),
    ]
