# Generated by Django 2.2.14 on 2020-11-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0012_tag_note_transition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagnote',
            options={'verbose_name': 'tags and notes', 'verbose_name_plural': 'tags and notes'},
        ),
    ]
