# Generated by Django 2.2.17 on 2021-02-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0014_changerecord_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerecord',
            name='record_natural',
            field=models.CharField(blank=True, db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='changerecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='changerecord',
            index=models.Index(fields=['record_type', 'record_pk'], name='mibios_chan_record__7aceb3_idx'),
        ),
    ]
