# Generated by Django 2.2.20 on 2021-06-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0015_changerecord_add_indicies'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='note',
            field=models.TextField(blank=True, default='', help_text='File meta info: origin of data, why was it imported etci.'),
        ),
    ]
