#!/bin/bash
set -euo pipefail

IMPORT_DIR=initial_import

if [[ -e ./manage.py ]];then dev=true; else dev=false; fi

if $dev; then
    manage_cmd=./manage.py
else
    manage_cmd=manage_mibios
fi

if [[ -e ./db.sqlite3 ]]; then
    $manage_cmd shell -c "from mibios import models; models.erase_all_data(verbose=True)"
else
    $manage_cmd migrate
fi
$manage_cmd update_users userlist
$manage_cmd import_data --data-set-name participants_list $IMPORT_DIR/participants.master.tsv --traceback
$manage_cmd import_data --data-set-name metadata --traceback --verbose-changes $IMPORT_DIR/metadata_new.run.drop.csv
$manage_cmd import_data --data-set-name MMP_manifest --sep , --traceback --verbose-changes --warn-on-error $IMPORT_DIR/MMP_manifest.20200511.csv
$manage_cmd import_data --data-set-name roberts_sample_list --verbose-changes --traceback $IMPORT_DIR/ugrads19.sample.master.csv
$manage_cmd import_data --data-set-name SCFA_indv $IMPORT_DIR/SCFA_indv.txt --traceback --verbose-changes
