#!/bin/bash
set -euo pipefail
if [[ -e ./manage.py ]];then dev=true; else dev=false; fi

if $dev; then
    manage_cmd=./manage.py
else
    manage_cmd=manage_mibios
fi

if [[ -e ./db.sqlite3 ]]; then
    $manage_cmd shell -c "from mibios import models; models.erase_all_data(verbose=True)"
else
    $manage_cmd migrate
    echo "Creating superuh user:"
     createsuperuser --username admin --email heinro@umich.edu
fi
$manage_cmd import_data --data-set-name participants_list participants.master.tsv
$manage_cmd import_meta --traceback --verbose-changes metadata_new.run.drop.csv
$manage_cmd import_MMP --traceback --verbose-changes MMP_manifest.20200511.csv
$manage_cmd import_sample_master --verbose-changes --traceback ugrads19.sample.master.csv
$manage_cmd import_data --data-set-name SCFA_indv SCFA_indv.txt 
