#!/bin/bash
set -euo pipefail
if [[ -e ./var/db.sqlite3 ]]; then
    ./manage.py shell -c "from mibios import models; models.erase_all_data(verbose=True)"
else
    ./manage.py migrate
    echo "Creating superuh user:"
    ./manage.py createsuperuser --username admin --email heinro@umich.edu
fi
./manage.py import_meta --traceback --verbose-changes metadata_new.run.drop.csv
./manage.py import_MMP --traceback --verbose-changes MMP_manifest.20200511.csv
./manage.py import_sample_master --verbose-changes --traceback ugrads19.sample.master.csv
