# Generated by Django 2.2.12 on 2020-05-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FecalSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('participant', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxid', models.PositiveIntegerField()),
                ('organism', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hmb.ASV')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('number', models.PositiveSmallIntegerField()),
                ('path', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'ordering': ['serial', 'number'],
                'unique_together': {('serial', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('control', models.CharField(blank=True, choices=[('mock', 'mock'), ('water', 'water'), ('blank', 'blank'), ('plate', 'plate'), ('other', 'other')], max_length=50)),
                ('r1_file', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('r2_file', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('plate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plate_position', models.CharField(blank=True, max_length=10)),
                ('snumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.ManyToManyField(to='hmb.Note')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmb.SequencingRun')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmb.FecalSample')),
            ],
            options={
                'ordering': ['run__serial', 'run__number', 'name'],
                'unique_together': {('run', 'plate', 'plate_position'), ('run', 'snumber')},
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('3', 'fall'), ('4', 'winter')], max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['year', 'season'],
                'unique_together': {('season', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(blank=True, max_length=50)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=200)),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hmb.Diet')),
                ('note', models.ManyToManyField(to='hmb.Note')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hmb.Semester')),
            ],
            options={
                'ordering': ['semester', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='note',
            field=models.ManyToManyField(to='hmb.Note'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmb.Participant'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hmb.Week'),
        ),
        migrations.AddField(
            model_name='diet',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmb.Week'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asv', models.ManyToManyField(to='hmb.ASV')),
                ('seqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmb.Sequencing')),
            ],
        ),
        migrations.CreateModel(
            name='BreathSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gases', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmb.Participant')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hmb.Week')),
            ],
        ),
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cytokines', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmb.Participant')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hmb.Week')),
            ],
        ),
        migrations.AddField(
            model_name='asv',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hmb.Taxon'),
        ),
        migrations.AlterUniqueTogether(
            name='fecalsample',
            unique_together={('participant', 'number')},
        ),
    ]
