# Generated by Django 2.2.12 on 2020-06-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet',
            options={'ordering': ('supplement', 'frequency', 'dose')},
        ),
        migrations.AlterModelOptions(
            name='sequencing',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='diet',
            name='dose',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='total dose grams'),
        ),
        migrations.AddField(
            model_name='diet',
            name='frequency',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='diet',
            name='supplement',
            field=models.CharField(blank=True, max_length=200, verbose_name='supplement consumed'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='acetate_abs',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Acetate_mM'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='acetate_rel',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Acetate_mmol_kg'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='bristol',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='butyrate_abs',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Butyrate_mM'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='butyrate_rel',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Butyrate_mmol_kg'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='final_weight',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='propionate_abs',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Propionate_mM'),
        ),
        migrations.AddField(
            model_name='fecalsample',
            name='propionate_rel',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True, verbose_name='Propionate_mmol_kg'),
        ),
        migrations.AddField(
            model_name='participant',
            name='quantity_compliant',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('Quantity_compliant', 'Quantity_compliant'), ('no', 'no'), ('none', 'none'), ('unknown', 'unknown'), ('yes', 'yes')], help_text='Did the participant consumed at least 75% of the starch they were prescribed?', max_length=30),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='r1_file',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sequencing',
            name='r2_file',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='diet',
            unique_together={('frequency', 'dose', 'supplement')},
        ),
        migrations.RemoveField(
            model_name='diet',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='week',
        ),
    ]
