# Generated by Django 2.2.12 on 2020-06-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fecalsample',
            options={'ordering': ('participant', 'number')},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['semester', 'name']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year', '-term']},
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='acetate_abs',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Acetate_mM'),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='acetate_rel',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Acetate_mmol_kg'),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='butyrate_abs',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Butyrate_mM'),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='butyrate_rel',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Butyrate_mmol_kg'),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='final_weight',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='propionate_abs',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Propionate_mM'),
        ),
        migrations.AlterField(
            model_name='fecalsample',
            name='propionate_rel',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Propionate_mmol_kg'),
        ),
    ]
