# Generated by Django 3.2.16 on 2022-12-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glamr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='collection_ts_partial',
            field=models.CharField(blank=True, choices=[('date_only', 'date_only'), ('year_only', 'year_only'), ('month_only', 'month_only'), ('', '')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project_id',
            field=models.CharField(blank=True, default='', help_text='Project accession, e.g. NCBI bioproject', max_length=32),
        ),
    ]
