# Generated by Django 3.2.16 on 2023-01-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umrad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compoundrecord',
            name='accession',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='compoundrecord',
            name='formula',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='compoundrecord',
            name='mass',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
