# Generated by Django 2.2.24 on 2022-01-21 22:30

from django.db import migrations, models
import django.db.models.deletion
import mibios.models
import mibios_umrad.fields
import mibios_umrad.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='CompoundEntry',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=40, unique=True)),
                ('db', models.CharField(choices=[('Biocyc', 'b'), ('ChEBI', 'c'), ('HMDB', 'h'), ('InChI', 'i'), ('KEGG', 'k'), ('PubChem', 'p')], db_index=True, max_length=1)),
                ('formula', models.CharField(blank=True, max_length=32)),
                ('charge', models.SmallIntegerField(blank=True, null=True)),
                ('mass', models.CharField(blank=True, max_length=16)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios_umrad.Compound')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='CompoundName',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['entry'],
                'abstract': False,
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='FunctionName',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['entry'],
                'abstract': False,
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'subcellular location',
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['entry'],
                'abstract': False,
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='ReactionEntry',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', mibios_umrad.fields.AccessionField()),
                ('db', models.CharField(choices=[('Biocyc', 'b'), ('KEGG', 'k'), ('RHEA', 'r')], db_index=True, max_length=1)),
                ('bi_directional', models.BooleanField(blank=True, null=True)),
                ('left', models.ManyToManyField(related_name='to_reaction', to='mibios_umrad.CompoundEntry')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios_umrad.Reaction')),
                ('right', models.ManyToManyField(related_name='from_reaction', to='mibios_umrad.CompoundEntry')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='RefDBEntry',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', mibios_umrad.fields.AccessionField()),
                ('db', models.CharField(db_index=True, max_length=4)),
            ],
            options={
                'verbose_name': 'Ref DB Entry',
                'verbose_name_plural': 'Ref DB Entries',
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='TaxName',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.PositiveSmallIntegerField(choices=[(0, 'root'), (1, 'domain'), (2, 'phylum'), (3, 'class'), (4, 'order'), (5, 'family'), (6, 'genus'), (7, 'species'), (8, 'strain')])),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'taxonomic name',
                'unique_together': {('rank', 'name')},
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('taxid', models.PositiveIntegerField(unique=True)),
                ('domain', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_dom_rel', to='mibios_umrad.TaxName')),
                ('family', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_fam_rel', to='mibios_umrad.TaxName')),
                ('genus', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_gen_rel', to='mibios_umrad.TaxName')),
                ('klass', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_cls_rel', to='mibios_umrad.TaxName')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_ord_rel', to='mibios_umrad.TaxName')),
                ('phylum', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_phy_rel', to='mibios_umrad.TaxName')),
                ('species', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_sp_rel', to='mibios_umrad.TaxName')),
                ('strain', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_str_rel', to='mibios_umrad.TaxName')),
            ],
            options={
                'verbose_name_plural': 'taxa',
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='Uniprot',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', mibios_umrad.fields.AccessionField(verbose_name='uniprot id')),
            ],
            options={
                'verbose_name': 'Uniprot',
                'verbose_name_plural': 'Uniprot',
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.CreateModel(
            name='UniRef100',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', mibios_umrad.fields.AccessionField(prefix='UNIREF100_')),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('uniref90', mibios_umrad.fields.AccessionField(prefix='UNIREF90_', unique=False)),
                ('signal_peptide', models.CharField(blank=True, default='', max_length=32)),
                ('tms', models.CharField(blank=True, default='', max_length=128)),
                ('dna_binding', models.CharField(blank=True, default='', max_length=128)),
                ('tcdb', models.CharField(blank=True, default='', max_length=128)),
                ('biocyc_reaction', models.ManyToManyField(related_name='uniref_biocyc', to='mibios_umrad.ReactionEntry')),
                ('function_name', models.ManyToManyField(to='mibios_umrad.FunctionName')),
                ('function_ref', models.ManyToManyField(to='mibios_umrad.RefDBEntry')),
                ('kegg_reaction', models.ManyToManyField(related_name='uniref_kegg', to='mibios_umrad.ReactionEntry')),
                ('metal_binding', models.ManyToManyField(to='mibios_umrad.Metal')),
                ('rhea_reaction', models.ManyToManyField(related_name='uniref_rhea', to='mibios_umrad.ReactionEntry')),
                ('subcellular_location', models.ManyToManyField(to='mibios_umrad.Location')),
                ('taxon', models.ManyToManyField(to='mibios_umrad.Taxon')),
                ('trans_compound', models.ManyToManyField(related_name='uniref_trans', to='mibios_umrad.CompoundEntry')),
                ('uniprot', models.ManyToManyField(to='mibios_umrad.Uniprot')),
            ],
            options={
                'verbose_name': 'UniRef100',
                'verbose_name_plural': 'UniRef100',
            },
            bases=(models.Model, mibios_umrad.model_utils.LoadMixin),
        ),
        migrations.AddField(
            model_name='compoundentry',
            name='name',
            field=models.ManyToManyField(to='mibios_umrad.CompoundName'),
        ),
    ]
