# Generated by Django 2.2.26 on 2022-05-23 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mibios.models
import mibios_umrad.fields
import mibios_umrad.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'distinct compound',
            },
            managers=[
                ('loader', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CompoundEntry',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=40, unique=True)),
                ('db', models.CharField(choices=[('b', 'Biocyc'), ('c', 'ChEBI'), ('h', 'HMDB'), ('i', 'InChi'), ('k', 'KEGG'), ('p', 'PubChem')], db_index=True, max_length=1)),
                ('formula', models.CharField(blank=True, max_length=32)),
                ('charge', models.SmallIntegerField(blank=True, null=True)),
                ('mass', models.CharField(blank=True, max_length=16)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='mibios_umrad.Compound', verbose_name='distinct compound')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CompoundName',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['entry'],
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='FuncRefDBEntry',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', mibios_umrad.fields.AccessionField()),
                ('db', models.CharField(choices=[('cog', 'COG'), ('ec', 'EC'), ('go', 'GO'), ('ipr', 'InterPro'), ('pfam', 'Pfam'), ('tcdb', 'TCDB'), ('tigr', 'TIGR')], db_index=True, max_length=4)),
            ],
            options={
                'verbose_name': 'Function Ref DB Entry',
                'verbose_name_plural': 'Func Ref DB Entries',
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='FunctionName',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['entry'],
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'subcellular location',
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['entry'],
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'distinct reaction',
            },
            managers=[
                ('loader', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReactionEntry',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', mibios_umrad.fields.AccessionField()),
                ('db', models.CharField(choices=[('b', 'Biocyc'), ('k', 'KEGG'), ('r', 'RHEA')], db_index=True, max_length=1)),
                ('bi_directional', models.BooleanField(blank=True, null=True)),
                ('left', models.ManyToManyField(related_name='to_reaction', to='mibios_umrad.CompoundEntry')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios_umrad.Reaction')),
                ('right', models.ManyToManyField(related_name='from_reaction', to='mibios_umrad.CompoundEntry')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('rank', models.PositiveSmallIntegerField(choices=[(0, 'root'), (1, 'domain'), (2, 'phylum'), (3, 'class'), (4, 'order'), (5, 'family'), (6, 'genus'), (7, 'species'), (8, 'strain')])),
                ('lineage', models.CharField(max_length=256)),
                ('ancestors', models.ManyToManyField(related_name='descendants', to='mibios_umrad.Taxon')),
            ],
            options={
                'verbose_name_plural': 'taxa',
                'abstract': False,
                'default_manager_name': 'objects',
                'unique_together': {('rank', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Uniprot',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', mibios_umrad.fields.AccessionField(verbose_name='uniprot id')),
            ],
            options={
                'verbose_name': 'Uniprot',
                'verbose_name_plural': 'Uniprot',
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='UniRef100',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('accession', mibios_umrad.fields.AccessionField(prefix='UNIREF100_')),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
                ('uniref90', mibios_umrad.fields.AccessionField(prefix='UNIREF90_', unique=False)),
                ('signal_peptide', models.CharField(blank=True, default='', max_length=32)),
                ('tms', models.CharField(blank=True, default='', max_length=128)),
                ('dna_binding', models.CharField(blank=True, default='', max_length=128)),
                ('tcdb', models.CharField(blank=True, default='', max_length=128)),
                ('biocyc_reactions', models.ManyToManyField(related_name='uniref_biocyc', to='mibios_umrad.ReactionEntry')),
                ('function_names', models.ManyToManyField(to='mibios_umrad.FunctionName')),
                ('function_refs', models.ManyToManyField(to='mibios_umrad.FuncRefDBEntry')),
                ('kegg_reactions', models.ManyToManyField(related_name='uniref_kegg', to='mibios_umrad.ReactionEntry')),
                ('lineage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios_umrad.Taxon')),
                ('metal_binding', models.ManyToManyField(to='mibios_umrad.Metal')),
                ('rhea_reactions', models.ManyToManyField(related_name='uniref_rhea', to='mibios_umrad.ReactionEntry')),
                ('subcellular_locations', models.ManyToManyField(to='mibios_umrad.Location')),
                ('taxa', models.ManyToManyField(related_name='classified_uniref100', to='mibios_umrad.Taxon')),
                ('trans_compounds', models.ManyToManyField(related_name='uniref_trans', to='mibios_umrad.CompoundEntry')),
                ('uniprot', models.ManyToManyField(to='mibios_umrad.Uniprot')),
            ],
            options={
                'verbose_name': 'UniRef100',
                'verbose_name_plural': 'UniRef100',
            },
            bases=(mibios_umrad.model_utils.LoadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaxID',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('taxid', models.PositiveIntegerField(unique=True, verbose_name='NCBI taxid')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios_umrad.Taxon')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='funcrefdbentry',
            name='names',
            field=models.ManyToManyField(to='mibios_umrad.FunctionName'),
        ),
        migrations.AddField(
            model_name='compoundentry',
            name='names',
            field=models.ManyToManyField(to='mibios_umrad.CompoundName'),
        ),
    ]
