# Generated by Django 2.2.24 on 2021-12-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_umrad', '0002_auto_20211217_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniref100',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
