# Generated by Django 2.2.24 on 2022-01-06 03:18

from django.db import migrations
import mibios_umrad.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_umrad', '0003_auto_20211222_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cog',
            name='accession',
            field=mibios_umrad.fields.AccessionField(),
        ),
    ]
