# Generated by Django 2.2.26 on 2022-06-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_umrad', '0001_initial'),
        ('mibios_omics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contigcluster',
            name='taxon',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='taxon',
        ),
        migrations.AddField(
            model_name='contigcluster',
            name='taxid',
            field=models.ManyToManyField(related_name='classified_contigcluster', to='mibios_umrad.TaxID'),
        ),
        migrations.AddField(
            model_name='gene',
            name='taxid',
            field=models.ManyToManyField(related_name='classified_gene', to='mibios_umrad.TaxID'),
        ),
    ]
