# Generated by Django 2.2.26 on 2022-08-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_omics', '0003_auto_20220806_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplegroup',
            name='short_name',
            field=models.CharField(blank=True, default=None, help_text='a short name or description, for internal use, not (necessarily) for public display', max_length=64, null=True, unique=True),
        ),
    ]
