# Generated by Django 2.2.14 on 2020-08-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_seq', '0003_move_note_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencing',
            name='oldnote',
        ),
    ]
