# Generated by Django 2.2.14 on 2020-09-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibios', '0010_auto_20200923_1607'),
        ('mibios_seq', '0006_add_analysis_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbundanceImportFile',
            fields=[
                ('importfile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mibios.ImportFile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mibios_seq.AnalysisProject')),
            ],
            bases=('mibios.importfile',),
        ),
    ]
