# Generated by Django 2.2.14 on 2020-10-08 14:55
# and renamed and modified

from django.db import migrations, models
import django.db.models.deletion
import mibios.models


class Migration(migrations.Migration):
    """
    Part 2 of OTU transition

    The Sequence model is added to keep track of sequences. Accordingly the
    Strain model switches its FK from OTU to Sequence, but no data migration is
    needed as that table has no data in it currently.  The sequencing data from
    OTU is transfered to the new table.

    Part 3 will remove sequence data from OTUs.
    """

    dependencies = [
        ('mibios', '0010_auto_20200923_1607'),
        ('mibios_seq', '0008_rename_asv_otu'),
    ]

    def forward(apps, schema_editor):
        """
        Copy data from OTU into Sequencing table

        Blanks corresponding data from OTU record
        """
        Sequence = apps.get_model('mibios_seq', 'Sequence')
        OTU = apps.get_model('mibios_seq', 'OTU')

        for i in OTU.objects.select_related('taxon'):
            seq = Sequence(
                taxon=i.taxon,
                seq=i.sequence,
            )
            seq.save()
            i.sequence_fk = seq
            i.taxon = None
            i.sequence = ''
            i.save()

    def reverse(apps, schema_editor):
        """
        Copy data from Sequence table back into OTU records
        """
        Sequence = apps.get_model('mibios_seq', 'Sequence')
        OTU = apps.get_model('mibios_seq', 'OTU')
        for i in OTU.objects.select_related('sequence_fk'):
            i.sequence = i.sequence_fk.seq
            i.taxon = i.sequence_fk.taxon
            i.sequence_fk.delete()
            i.sequence_fk = None
            i.save()

        if Sequence.objects.exists():
            print('WARNING: not all Sequence records were deleted')

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='asv',
        ),
        migrations.AlterField(
            model_name='otu',
            name='sequence',
            field=models.CharField(max_length=300, blank=True),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', mibios.models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(editable=False, max_length=300, unique=True, verbose_name='sequence')),
                ('history', models.ManyToManyField(to='mibios.ChangeRecord')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios_seq.Taxonomy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='otu',
            name='sequence_fk',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios_seq.Sequence'),
        ),
        migrations.AddField(
            model_name='strain',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mibios_seq.Sequence'),
        ),
        migrations.RunPython(forward, reverse),
    ]
