# Generated by Django 2.2.14 on 2020-10-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Part 3 of the OTU transition
    """

    dependencies = [
        ('mibios_seq', '0009_add_sequence_model'),
    ]

    def forward(apps, schema_editor):
        """
        Populate kind, prefix in OTU records

        We assume that all OTU records are former ASVs, so we have a valid
        number and kind and prefix are obvious.  Project remains NULL/None
        since ASV won't belong to a project, (they are multi-project)
        """
        OTU = apps.get_model('mibios_seq', 'OTU')

        ASV_KIND = 'ASV'

        OTU.objects.all().update(kind=ASV_KIND, prefix='ASV')

    operations = [
        migrations.AlterModelOptions(
            name='otu',
            options={'ordering': ('prefix', 'number')},
        ),
        migrations.RenameField(
            model_name='abundance',
            old_name='asv',
            new_name='otu',
        ),
        migrations.AddField(
            model_name='otu',
            name='kind',
            field=models.CharField(choices=[('ASV', 'ASV'), ('97pct', '97% OTU')], default='ASV', max_length=5, verbose_name='OTU type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otu',
            name='prefix',
            field=models.CharField(default='ASV', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otu',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mibios_seq.AnalysisProject'),
        ),
        migrations.AlterField(
            model_name='otu',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='abundance',
            unique_together={('otu', 'sequencing', 'project'), ('name', 'sequencing', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='otu',
            unique_together={('prefix', 'number', 'project')},
        ),
        migrations.RemoveField(
            model_name='otu',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='otu',
            name='taxon',
        ),
        migrations.RenameField(
            model_name='otu',
            old_name='sequence_fk',
            new_name='sequence',
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
