# Generated by Django 2.2.14 on 2020-10-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_seq', '0011_rm_name_from_abundance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisproject',
            old_name='asv',
            new_name='otu',
        ),
        migrations.AlterField(
            model_name='otu',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_otus', to='mibios_seq.AnalysisProject'),
        ),
    ]
