# Generated by Django 2.2.14 on 2020-10-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_seq', '0012_auto_20201008_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abundance',
            options={'verbose_name_plural': 'abundance'},
        ),
        migrations.AlterModelOptions(
            name='otu',
            options={'ordering': ('prefix', 'number'), 'verbose_name': 'OTU'},
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name_plural': 'taxonomy'},
        ),
    ]
