# Generated by Django 2.2.14 on 2020-10-16 15:05
# and modified

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_seq', '0014_move_otu_type_field'),
        ('mibios', '0012_tag_note_transition'),
    ]

    def forward(apps, schema_editor):
        """
        Copy notes from SeqNote to TagNote
        """
        SeqNote = apps.get_model('mibios_seq', 'SeqNote')
        TagNote = apps.get_model('mibios', 'TagNote')
        for old in SeqNote.objects.all():
            new = TagNote.objects.create(name=old.name, text=old.text)
            new.sequencing_set.set(old.sequencing_set.all())
            new.history.set(old.history.all())

    def reverse(apps, schema_editor):
        """
        Copy TagNotes back into SeqNotes

        This operation will lose the tag information
        """
        SeqNote = apps.get_model('mibios_seq', 'SeqNote')
        TagNote = apps.get_model('mibios', 'TagNote')
        for i in TagNote.objects.all():
            obj = SeqNote.objects.create(name=i.name, text=i.text)
            obj.sequencing_set.set(i.sequencing_set.all())
            obj.history.set(i.history.all())

    operations = [
        migrations.AddField(
            model_name='sequencing',
            name='note_new',
            field=models.ManyToManyField(blank=True, to='mibios.TagNote'),
        ),
        migrations.RunPython(forward, reverse),
        migrations.RemoveField(
            model_name='sequencing',
            name='note',
        ),
        migrations.DeleteModel(
            name='SeqNote',
        ),
        migrations.RenameField(
            model_name='sequencing',
            old_name='note_new',
            new_name='note',
        ),
    ]
