# Generated by Django 2.2.14 on 2020-11-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_seq', '0015_tag_note_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='abundance',
            name='relative',
            field=models.FloatField(default=None, editable=False, null=True, verbose_name='relative abundance'),
        ),
    ]
