# Generated by Django 2.2.14 on 2020-11-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibios_seq', '0017_auto_20201112_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisproject',
            name='sequencing',
            field=models.ManyToManyField(editable=False, related_name='project', through='mibios_seq.Abundance', to='mibios_seq.Sequencing'),
        ),
        migrations.AddField(
            model_name='sequencing',
            name='otu',
            field=models.ManyToManyField(editable=False, through='mibios_seq.Abundance', to='mibios_seq.OTU'),
        ),
    ]
