# Originally generated by Django 2.2.17 on 2021-02-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Use a direct m2m relation between projects and sequencings

    Improved support for use case:
        Find all sequencings that were analysed by given project

    The current relation goes through Abundance which incurrs a much higher
    performance penalty.  This migration will populate the new intermediate
    table going forward.  The whole change requires that when abundance data is
    added after going forward, both intermediate tables have to be updated in a
    corrdinate fashion to stay consistent.

    The corrsponding change in the model is just the removal of the
    "through=Abundance" kwarg.  The makemigrations command will translate that
    into a AlterField but during the migration will raise with "you cannot
    alter to or from M2M fields, or add or remove through= on M2M fields".  So
    we do it in two steps: first remove the original field that goes through
    abundance.  That should not alter any schema or data.  Then we add a new
    field that looks just like the old on butdoen't go through anything.  At
    last we migrate the data.
    """

    dependencies = [
        ('mibios_seq', '0018_auto_20201119_1814'),
    ]

    def forward(apps, schema_editor):
        """
        Populate new intermediate table from Abundance

        For each project, if there is an non-zero abundance for a sequencing,
        then relate project to sequencing.
        """
        Sequencing = apps.get_model('mibios_seq', 'Sequencing')
        AnalysisProject = apps.get_model('mibios_seq', 'AnalysisProject')

        for i in AnalysisProject.objects.all():
            qs = Sequencing.objects.filter(abundance__project=i).distinct()
            i.sequencing.set(qs)

    operations = [
        migrations.RemoveField(
            model_name='analysisproject',
            name='sequencing',
        ),
        migrations.AddField(
            model_name='analysisproject',
            name='sequencing',
            field=models.ManyToManyField(
                editable=False,
                related_name='project',
                to='mibios_seq.Sequencing',
            ),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
